# Generated by Django 5.0.4 on 2024-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
